# Contact E-Mail (Public!)
email: "ethericall.help@gmail.com"

# Site name and main title
name: "Beta Ethericall"
title: "Beta Ethericall"

# Site Description
description: "Ethericall official website"

# Discord server invite
discord: "https://discord.gg/wyfzxHA"
# Theme of Discord widget
discord-theme: "dark"
# Discord support server ID
discord-id: "623945078506782762"

# Site base-url (no slash at end, not link!)
baseurl: ""

# Site url (link or dir eg. "/site" or "https://igorkowalczyk.github.io
url: ""